# ──────────────────────────────────────────────────────────────────────────────
# Multi-stage Dockerfile for sudoku-generator (Next.js 16 standalone)
#
# Stages:
#   deps    — install npm dependencies (layer-cached on lockfile change)
#   builder — compile the production bundle (next build)
#   runner  — minimal Alpine image that runs server.js
#
# Requirements:
#   next.config.mjs must have  output: 'standalone'
#
# Usage:
#   docker build -t sudoku-generator .
#   docker run -p 3000:3000 sudoku-generator
#   docker compose up                         # via docker-compose.yml
# ──────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Install dependencies ─────────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app

# Copying lockfiles separately gives Docker a cache layer that is only
# invalidated when dependencies change — not on every source code edit.
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts


# ── Stage 2: Build production bundle ──────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

# Inherit installed modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy full source
COPY . .

# Opt out of Next.js anonymous telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Ensure public/ exists even if the repo has no assets — the standalone COPY
# in the runner stage requires the directory to be present.
RUN mkdir -p public

RUN npm run build


# ── Stage 3: Production runner (minimal image) ────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

# Run as a dedicated non-root user (defence in depth)
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Static public assets
COPY --from=builder /app/public ./public

# Standalone server (server.js + minimal node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Compiled static chunks referenced by server.js at runtime
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# Health check — Node.js HTTP client, no extra tools required in Alpine
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/',r=>process.exit(r.statusCode===200?0:1))"

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
